;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-delete-forward
        c-electric-paren
        c-electric-semi&comma
        jde-backward-kill-camel-tok
        jde-kill-camel-tok
        kill-region
        org-beginning-of-line
        org-end-of-line
        org-force-self-insert
        org-kill-line
        org-self-insert-command
        org-yank
        string-rectangle
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        ))
